import React, { useState, useEffect } from 'react';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,
  LineChart, Line, ComposedChart, Area
} from 'recharts';
import { FolderUp, TrendingUp, Users, AlertTriangle } from 'lucide-react';

export default function DriveDashboard() {
  const [activeTab, setActiveTab] = useState('LIMA');
  const [maestriaData, setMaestriaData] = useState({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadDriveData = async () => {
      try {
        setLoading(true);
        // We use dynamic imports to load the JSON files generated by our script
        const indexFile = await import('../data/reportes_drive/index.json');
        
        // Cargar sedes principales
        const pLima = import('../data/reportes_drive/MAESTRIA LIMA.json');
        const pGye = import('../data/reportes_drive/MAESTRIA GYE.json');
        const pQuito = import('../data/reportes_drive/MAESTRIA QUITO.json');
        const pCuenca = import('../data/reportes_drive/MAESTRIA CUENCA.json');

        const [rLima, rGye, rQuito, rCuenca] = await Promise.all([pLima, pGye, pQuito, pCuenca]);

        setMaestriaData({
          LIMA: parseMaestriaData(rLima.default['2026']),
          GYE: parseMaestriaData(rGye.default['2026'] || rGye.default['Sheet1']),
          QUITO: parseMaestriaData(rQuito.default['2026'] || rQuito.default['Sheet1']),
          CUENCA: parseMaestriaData(rCuenca.default['2026'] || rCuenca.default['Sheet1']),
        });

      } catch (err) {
        console.error('Error loading drive data:', err);
      } finally {
        setLoading(false);
      }
    };
    loadDriveData();
  }, []);

  const parseMaestriaData = (sheetData) => {
    if (!sheetData) return [];
    
    const findRow = (name) => sheetData.find(r => typeof r.__EMPTY === 'string' && r.__EMPTY.toLowerCase().includes(name.toLowerCase())) || {};
    
    const fechas = findRow('FECHA');
    const llegaron = findRow('PX que llegaron');
    const terminaron = findRow('Terminaron');
    const desercion = findRow('Deserci');
    const declaracion = findRow('Declaraci');

    const chartData = [];
    Object.keys(fechas).forEach(key => {
      if (key.startsWith('__EMPTY_')) {
        chartData.push({
          name: fechas[key],
          Llegaron: llegaron[key] || 0,
          Terminaron: terminaron[key] || 0,
          Deserciones: desercion[key] || 0,
          Declaracion: declaracion[key] || 0,
        });
      }
    });
    return chartData;
  };

  if (loading) {
    return (
      <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--crear-gold)' }}>
        Cargando Dashboards Regionales desde Google Drive...
      </div>
    );
  }

  const currentData = maestriaData[activeTab] || [];
  
  // Calculate Totals for the current sede
  const totalLlegaron = currentData.reduce((acc, curr) => acc + (Number(curr.Llegaron) || 0), 0);
  const totalDeserciones = currentData.reduce((acc, curr) => acc + (Number(curr.Deserciones) || 0), 0);
  const tasaDesercion = totalLlegaron > 0 ? ((totalDeserciones / totalLlegaron) * 100).toFixed(1) : 0;

  return (
    <div style={{ marginTop: '2rem', background: 'rgba(255,255,255,0.02)', padding: '1.5rem', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.05)' }}>
      
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem', marginBottom: '1.5rem' }}>
        <FolderUp size={28} className="text-gold" />
        <div>
          <h3 style={{ margin: 0, color: 'var(--crear-gold)' }}>Reportes Consolidados (Maestría)</h3>
          <p style={{ margin: 0, fontSize: '0.85rem', color: 'var(--text-muted)' }}>Sincronizado desde Google Drive (Hojas de Cálculo)</p>
        </div>
      </div>

      <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1.5rem', overflowX: 'auto', paddingBottom: '0.5rem' }}>
        {Object.keys(maestriaData).map(sede => (
          <button 
            key={sede}
            onClick={() => setActiveTab(sede)}
            style={{
              padding: '0.5rem 1.5rem',
              background: activeTab === sede ? 'var(--crear-gold)' : 'rgba(255,255,255,0.05)',
              color: activeTab === sede ? '#000' : '#fff',
              border: 'none',
              borderRadius: '20px',
              fontWeight: 'bold',
              cursor: 'pointer',
              transition: 'all 0.2s ease'
            }}
          >
            {sede}
          </button>
        ))}
      </div>

      {/* Summary Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem', marginBottom: '2rem' }}>
        <div style={{ background: 'rgba(52, 168, 83, 0.1)', padding: '1rem', borderRadius: '8px', border: '1px solid rgba(52, 168, 83, 0.3)' }}>
          <div style={{ color: '#34a853', fontSize: '0.8rem', fontWeight: 'bold', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Users size={16}/> TOTAL LLEGARON</div>
          <div style={{ fontSize: '1.8rem', fontWeight: 'bold', color: '#fff' }}>{totalLlegaron}</div>
        </div>
        
        <div style={{ background: 'rgba(239, 68, 68, 0.1)', padding: '1rem', borderRadius: '8px', border: '1px solid rgba(239, 68, 68, 0.3)' }}>
          <div style={{ color: '#ef4444', fontSize: '0.8rem', fontWeight: 'bold', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><AlertTriangle size={16}/> DESERCIONES TOTALES</div>
          <div style={{ fontSize: '1.8rem', fontWeight: 'bold', color: '#fff' }}>{totalDeserciones}</div>
        </div>

        <div style={{ background: 'rgba(245, 158, 11, 0.1)', padding: '1rem', borderRadius: '8px', border: '1px solid rgba(245, 158, 11, 0.3)' }}>
          <div style={{ color: '#f59e0b', fontSize: '0.8rem', fontWeight: 'bold', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><TrendingUp size={16}/> TASA DE DESERCIÓN</div>
          <div style={{ fontSize: '1.8rem', fontWeight: 'bold', color: '#fff' }}>{tasaDesercion}%</div>
        </div>
      </div>

      {currentData.length > 0 ? (
        <div style={{ height: '350px', width: '100%', background: 'rgba(0,0,0,0.3)', padding: '1rem', borderRadius: '8px' }}>
          <ResponsiveContainer width="100%" height="100%">
            <ComposedChart data={currentData} margin={{ top: 20, right: 30, left: 0, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" />
              <XAxis dataKey="name" stroke="#cbd5e1" fontSize={12} tickMargin={10} />
              <YAxis stroke="#cbd5e1" fontSize={12} />
              <Tooltip 
                contentStyle={{ backgroundColor: 'rgba(15, 23, 42, 0.9)', border: '1px solid rgba(255,255,255,0.1)', color: '#fff', borderRadius: '8px' }} 
              />
              <Legend wrapperStyle={{ paddingTop: '20px' }} />
              <Bar dataKey="Llegaron" fill="var(--crear-blue)" name="Llegaron" radius={[4, 4, 0, 0]} />
              <Bar dataKey="Terminaron" fill="var(--crear-gold)" name="Terminaron" radius={[4, 4, 0, 0]} />
              <Line type="monotone" dataKey="Deserciones" stroke="#ef4444" strokeWidth={3} name="Deserciones" dot={{ r: 5 }} />
            </ComposedChart>
          </ResponsiveContainer>
        </div>
      ) : (
        <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-muted)' }}>
          No se encontró historial para esta sede en el reporte importado de Google Drive.
        </div>
      )}

    </div>
  );
}
